#!/bin/bash
sudo yum update -y
sudo yum  install -y wget unzip tar xz curl ipset docker ntp
sudo systemctl start docker
sudo groupadd nogroup
sudo groupadd docker
sudo systemctl stop firewalld && sudo systemctl disable firewalld
sudo systemctl stop dnsmasq && sudo systemctl disable dnsmasq.service
sudo sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
sudo mkdir /tmp/dcos && cd /tmp/dcos
sudo curl -O http://130.61.109.222:80/dcos_install.sh
sudo bash dcos_install.sh slave_public
